" High level
set nocompatible        " Turn of old vi compatibility mode
set modelines=0         " Disable modelines
set encoding=utf-8      " Just make everything boring

" Buffers
set hidden              " Allow unsaved buffers off screen

" General
set showcmd             " Show commands as typing them
set number              " Show line numbers
set relativenumber      " Show relative line numbers
set linebreak           " Break lines at word (requires Wrap lines)
set textwidth=0         " Do not change buffer text when wrapping
set showmatch           " Highlight matching brace
set visualbell          " Use visual bell (no beeping)
set cursorline          " Highlight current line
set title               " Set window title if possible
set shortmess-=S        " Display search match index

set hlsearch            " Highlight all search results
set smartcase           " Enable smart-case search
set ignorecase          " Always case-insensitive

" Tabs
set tabstop=2           " Size of tab in spaces
set shiftwidth=2        " Number of auto-indent spaces
set expandtab           " Insert spaces for tab key
set smartindent         " Enable smart-indent
set softtabstop=0       " Number of spaces per Tab

" Whitespace
set list                " Display whitespace
set listchars=tab:▸\ ,trail:␣

" Aesthetics
set fillchars=vert:│

" Advanced
set undolevels=1000     " Number of undo levels

" Enable code folding
set foldmethod=indent
set nofoldenable        " Do not fold on opening
set foldnestmax=10
set foldlevel=0         " Start folding at this level
set foldminlines=0      " Fold single line regions
let g:markdown_folding = 1

" Show more context
set scrolloff=6

" Enable mouse
set mouse=a

" Splits in more natural location
set splitbelow
set splitright

" enable 24bit true color
if (has("termguicolors"))
  set termguicolors
endif

" Expect terminal emulator to display things quickly
if (has("termguicolors"))
  set ttyfast
endif

" Correct italics
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

" Make netrw (file explorer) look sane
let g:netrw_liststyle = 3     " Nested view
let g:netrw_banner = 0        " No banner
let g:netrw_winsize = 20      " 20% width

" Prefer ripgrep over grep if available
if executable('rg')
  set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case\ --hidden
endif

" General file editing enhancements
filetype indent plugin on

" Specific file types
autocmd Filetype gitcommit setlocal textwidth=80
autocmd Filetype ruby setlocal colorcolumn=120
autocmd Filetype javascript setlocal colorcolumn=91
autocmd Filetype typescript setlocal colorcolumn=91
autocmd Filetype python setlocal colorcolumn=120

" Markdown
autocmd Filetype markdown noremap j gj
autocmd Filetype markdown noremap k gk
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!

" Key bindings

let mapleader = " "     " Change default leader from '\'

" Mappings:

" - Make copy consistent with other actions
nnoremap Y y$

" - More convenient way to increase/decrease folding
nnoremap zh zm
nnoremap zl zr

" - Retain selection when indenting
vnoremap < <gv
vnoremap > >gv

" - Save some LH typing
inoremap jk <Esc>

" - Visual mode quick duplicate
xnoremap D y'>pgv
" - Visual mode quick duplicate
xnoremap D y'>pgv

" - Highlight word under cursor but don't jump
nnoremap <silent> * :let @/ = '\<' . expand('<cword>') . '\>' <bar> set hls <cr>
" NOTE: Uses x register
xnoremap <silent> * "xy:<C-U>let @/ = '\V'.escape(@x, '\') <bar> set hls <cr>

" - Resize current window with arrow keys
nnoremap <Right> :vertical resize +2<CR>
nnoremap <Left> :vertical resize -2<CR>
nnoremap <Up> :resize +2<CR>
nnoremap <Down> :resize -2<CR>

" Leader mappings:

" - Save buffer
nnoremap <leader>w :write<CR>

" - Close window
nnoremap <leader>x :close<CR>

" - Close buffer
nnoremap <leader>D :bdelete<CR>

" - Close buffer but keep window
nnoremap <leader>d :bprevious \| bdelete #<CR>

" - Cycle through buffers
nnoremap <leader>j :bnext<CR>
nnoremap <leader>k :bprevious<CR>

" - Run the default build command
nnoremap <leader>b :Make<CR>

" - Fuzzy file search in project
nnoremap <leader>p :Files<CR>

" - Fuzzy file search open buffers
nnoremap <leader>P :Buffers<CR>

" - Fuzzy file search recent
nnoremap <leader>H :HISTORY<CR>

" - Fuzzy text search in buffer (in order)
nnoremap <leader>/ :BSLines<CR>

" - Fuzzy text search in buffer for selected text (in order)
" NOTE: Uses x register
xnoremap <leader>/ "xy:<C-U>BSLines =escape(getreg('x'), '\()[]+*{}^$')<CR><CR>

" - Fuzzy tag search in buffer
nnoremap <leader>? :BTags<CR>

" - Fuzzy text search in project
nnoremap <leader>f :RG<CR>

" - Fuzzy text search in project for word under cursor
" NOTE: <C-R><C-W> will not type text that's already there, which will match the
" "b" from the leading "\b"!
nnoremap <leader>F :RG \b<C-R>=expand('<cword>')<CR>\b<CR>

" - Fuzzy text search in project for selected text
" NOTE: Uses x register
xnoremap <leader>F "xy:<C-U>RG <C-R>=escape(getreg('x'), '\()[]+*{}^$')<CR><CR>

" - Display navigable file outline in local list
nnoremap <leader>so <Plug>(ShowLocalOutline)

" - Display file outline in new buffer
nnoremap <leader>sO <Plug>(ShowOutline)

" - Display file git history
nnoremap <leader>sl :Redir !git log --oneline -n 1000 -- %<CR>

" - Display file git blame
nnoremap <leader>sb :!git blame -- %<CR>

" - Search devdocs for word under cursor
nnoremap <leader>sd :SearchDevDocs <C-R>=expand('<cword>')<CR><CR>

" - Search devdocs for selected text
" NOTE: Uses x register
xnoremap <leader>sd "xy:<C-U>SearchDevDocs <C-R>=getreg('x')<CR><CR>

" - Search web for word under cursor
nnoremap <leader>sg :SearchWeb <C-R>=expand('<cword>')<CR><CR>

" - Search web for selected text
" NOTE: Uses x register
xnoremap <leader>sg "xy:<C-U>SearchWeb <C-R>=getreg('x')<CR><CR>

" - Search dictionary for word under cursor
nnoremap <leader>sw :SearchDictionary <C-R>=expand('<cword>')<CR><CR>

" - Search thesaurus for word under cursor
nnoremap <leader>st :SearchThesaurus <C-R>=expand('<cword>')<CR><CR>

" - Copy things about current buffer to clipboard
nnoremap <leader>cf :let @+ = expand("%") <BAR> redraw <BAR> echo 'Copied path to clipboard'<CR>

" - Quickly copy current file (leaves you in command mode)
nnoremap <leader>cp :! cp % %:h/

" - Open in Github
nnoremap <leader>- :GetCurrentBranchLink<CR>

" - Preview markdown
nnoremap <leader>m :! preview-markdown <C-R>=expand('%')<CR><CR>

" - Manually manage location list
nmap <leader>la <Plug>(LociAdd)
nmap <leader>lc <Plug>(LociClear)
nmap <leader>lr <Plug>(LociRead)
nmap <leader>lw <Plug>(LociWrite)

" - Writing presentations
nnoremap <leader>th <Plug>(ToiletBig)
nnoremap <leader>tH <Plug>(ToiletStandard)
nnoremap <leader>tf <Plug>(ToiletFuture)
nnoremap <leader>tF <Plug>(ToiletPagga)
nnoremap <leader>tb <Plug>(ToiletBorder)

" - Managing todo lists
nnoremap <leader>ti :put ='- [ ] <+ TODO +>'<CR>
nnoremap <leader>tt :keeppatterns s/\v\[([^\]]*)\]/\="[".(submatch(1)==" "?"x":" ")."]"/<CR>

" - Show highlight groups at the cursor
noremap <silent> <F10> <Plug>(SyntaxexplorerAtCursor)
noremap <leader>ss <Plug>(SyntaxexplorerStackAtCursor)

" .vimrc shortcuts
nnoremap <leader>ve :edit $MYVIMRC<CR>
nnoremap <leader>vr :source $MYVIMRC <BAR> redraw <BAR> echo 'Reloaded .vimrc'<CR>

" Github cli shortcuts
nnoremap <leader>gp :! gh pr create<CR>
nnoremap <leader>gs :! gh pr status<CR>
nnoremap <leader>gc :! gh pr checks<CR>

" tmux
nnoremap <leader>ter :silent . write ! tmux-send .right<CR>
xnoremap <leader>ter :silent . write ! tmux-send .right<CR>
nnoremap <leader>ty :silent . write ! tmux load-buffer -<CR>:echo 'Copied to tmux'<CR>
nnoremap <leader>tp :    read ! tmux show-buffer<CR>:echo 'Pasted from tmux'<CR>
nnoremap <leader>tP :.-1 read ! tmux show-buffer<CR>:echo 'Pasted from tmux'<CR>

" - Execute lines and append output
" Uses x register.
nnoremap <leader>eeb "xyy"xPj!!bash<CR>
xnoremap <leader>eeb "xy"xo<Esc>p!!bash<CR>gv
nnoremap <leader>eer "xyy"xPj!!ruby<CR>
xnoremap <leader>eer "xy"xo<Esc>p!!ruby<CR>gv
nnoremap <leader>eep "xyy"xPj!!python3<CR>
xnoremap <leader>eep "xy"xo<Esc>p!!python3<CR>gv

" - Execute current line (in shell)
nnoremap <leader>es :!<C-R>=escape(getline('.'), '%')<CR><CR>
nnoremap <leader>eS :!clear;<C-R>=escape(getline('.'), '%')<CR><CR>
vnoremap <leader>es :write !sh<CR>
vnoremap <leader>eS :write !sh<CR>

" Snippets
nnoremap <leader>is <Plug>(SnippetsInsert)

" Insert person from git
vnoremap <leader>ip <Plug>(GitReplaceWithPerson)

" - Refactor: Inline
" NOTE: Uses i and j registers, and i and j marks.
" Implementation deletes the target to @i and copies the variable name to @j
" then sets up a change to replace the variable with the target before deleting
" the declaration line(s).  Much of this is to cater for multiline values.
nmap <silent> <leader>ri viw<leader>ri
xnoremap <silent> <leader>ri 
  \:<C-U>'< mark i<CR>
  \:<C-U>'>+1 mark j<CR>
  \gv
  \"id
  \F=BviW
  \"jy
  \gv
  \:<C-U>let @/ = '\V'.escape(@j, '\') <BAR> set hls <CR>
  \cgni<Esc>
  \:'i,'j-1 delete<CR>
  \n
  \:echo 'Press . to replace each '.@j.' usage with '.@i<CR>

" fzf mappings:

" - Display mappings
nmap <leader><tab> <plug>(fzf-maps-n)
xmap <leader><tab> <plug>(fzf-maps-x)
omap <leader><tab> <plug>(fzf-maps-o)

" - Insert mode completion
" imap <c-x><c-k> <plug>(fzf-complete-word)
" imap <c-x><c-f> <plug>(fzf-complete-path)
" imap <c-x><c-l> <plug>(fzf-complete-line)

" Special non-leader mappings:

" - Find and select next placeholder
nnoremap <C-j> :keeppattern normal! /\v\<\+[^>]*\+\><C-v><CR><CR>vf><C-g>
smap <C-j> <Esc><C-j>
imap <C-j> <Esc><C-j>

" - Show presentation
noremap <silent> <F5> <Plug>(PresenterPresent)

" Fix syntax highlighting it goes wonky
nnoremap <F12> <Esc>:syntax sync fromstart<CR>
inoremap <F12> <C-o>:syntax sync fromstart<CR>

" Plugins (managed by `vim-plugin`)
" See `README.md` for bootstrap

call plug#begin('~/.vim/plugged')
Plug 'https://github.com/chrisbra/matchit'
Plug 'https://github.com/tpope/vim-sensible'
Plug 'https://github.com/tpope/vim-fugitive'
Plug 'https://github.com/tpope/vim-vinegar'
Plug 'https://github.com/tpope/vim-surround'
" Plug 'https://github.com/tpope/vim-rails'
Plug 'https://github.com/tpope/vim-repeat'
Plug 'https://github.com/tpope/vim-projectionist'
Plug 'https://github.com/tpope/vim-dispatch'
Plug 'https://github.com/tpope/vim-unimpaired'
Plug 'https://github.com/vim-airline/vim-airline'
Plug 'https://github.com/vim-airline/vim-airline-themes'
Plug 'https://github.com/airblade/vim-gitgutter'
Plug 'https://github.com/sheerun/vim-polyglot'
Plug 'https://github.com/haishanh/night-owl.vim'
Plug 'https://github.com/junegunn/fzf'
Plug 'https://github.com/junegunn/fzf.vim'
Plug 'https://github.com/knsh14/vim-github-link'
Plug 'https://github.com/junegunn/goyo.vim'
Plug 'https://github.com/junegunn/limelight.vim'
Plug 'https://github.com/wincent/terminus'
Plug 'https://github.com/psf/black'
Plug 'https://github.com/editorconfig/editorconfig-vim'
Plug 'https://github.com/mbbill/undotree.git'
Plug 'https://github.com/edwardsnjd/vim-lsp', { 'branch': 'before-init' }
call plug#end()

" enable the theme
colorscheme night-owl
let g:airline_theme='night_owl'

" LSP

function! <SID>ConfigureLsp() abort
  " Misc
  setlocal signcolumn=yes
  let g:lsp_format_sync_timeout = 1000

  " C-X C-O for LSP autocomplete
  setlocal omnifunc=lsp#complete

  " Use LSP not ctags
  if exists('+tagfunc')
    setlocal tagfunc=lsp#tagfunc
  endif

  " Informational mappings
  nmap <buffer> K <plug>(lsp-hover)
  nmap <buffer> [g <plug>(lsp-previous-diagnostic)
  nmap <buffer> ]g <plug>(lsp-next-diagnostic)
  nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> ge <plug>(lsp-document-diagnostics)
  nmap <buffer> gp <plug>(lsp-peek-definition)
  nmap <buffer> gr <plug>(lsp-references)
  nmap <buffer> gs <plug>(lsp-document-symbol-search)
  " Mutating mappings
  nmap <buffer> <leader>rf <plug>(lsp-document-format)
  nmap <buffer> <leader>rn <plug>(lsp-rename)
  nmap <buffer> <leader>rr <plug>(lsp-code-action)
  vmap <buffer> <leader>rr :LspCodeAction<CR>
endfunction

augroup lsp_install
  autocmd!
  autocmd User lsp_buffer_enabled call <SID>ConfigureLsp()
augroup END
