choco install git -y
choco install microsoft-windows-terminal -y
choco install vscode -y
choco install wsl2 -y
choco install fzf -y
choco install ripgrep -y
choco install bat -y
choco install wsl-ubuntu-2004 -y
choco install powertoys -y
choco install docker-desktop -y
choco install googlechrome -y
choco install dropbox -y
choco install keepassxc -y
choco install firacode -y
choco install vcxsrv -y
choco install screentogif -y
