choco install git.install --params "/GitAndUnixToolsOnPath" -y
choco install microsoft-windows-terminal -y
choco install vscode -y
choco install wsl2 -y
choco install fzf -y
choco install ripgrep -y
choco install bat -y
choco install wsl-ubuntu-2004 -y
choco install powertoys -y
choco install docker-desktop -y
choco install googlechrome -y
choco install dropbox -y
choco install keepassxc -y
choco install firacode -y
choco install vcxsrv -y
choco install screentogif -y
choco install zoom -y
choco install androidstudio -y
choco install fd -y
choco install gh -y
choco install tree -y
choco install scrcpy -y
choco install openvpn-connect -y
choco install openvpn -y
choco install vlc -y
choco install alacritty -y
choco install virtualbox -y
choco install picotorrent -y
choco install python3 -y
choco install unity-hub -y
choco install dotnet-sdk -y
choco install nomachine -y
