;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "qbittorrent"
        "ansible"
        "wl-clipboard"
        "keepassxc"
        "openscad"
        "w3m"
        "ansible"
        "visidata"
        "newsboat"
        "gnuplot"
        "feedgnuplot"
        "hledger"
        "openjdk"
        "graphviz"
        "nushell"
        "nmap"
        "pandoc"
        "moreutils"
        "encfs"
        "git-delta"
        "bat"
        "moreutils"
        "ripgrep"
        "pandoc"
        "du-dust"
        "hexyl"
        "ripgrep"
        "fd"
        "nmap"
        "universal-ctags"
        "recutils"
        "tmux"
        "htop"
        "syncthing"
        "curl"
        "glibc-locales"
        "nb"
        "gh"
        "fzf"
        "datamash"
        "gcal"
        "make"
        "entr"
        "stow"
        "rlwrap"
        "tree"
        "lf"
        "guile"
        "nss-certs"))
