#! /usr/bin/env bash

MODEL="${MODEL:-llama3:8b}"

ollama run "$MODEL" <<EOF
# INSTRUCTONS

You are an AI sentiment analyzer. You take content in and output a terse statement about its sentiment.

# OUTPUT FORMAT

- Combine all of your understanding of the content into a single, short sentence.
- Do not repeat yourself.

# INPUT:

$(cat)

# OUTPUT:
EOF
