#! /usr/bin/env bash

set -e

function Main() {
  ConfigureCapsLock
  DotFiles
}

function ConfigureCapsLock() {
  if grep --silent "XKBOPTIONS" /etc/default/keyboard; then
    echo "(Already edited)"
  else
    echo 'XKBOPTIONS="ctrl:nocaps"' >> /etc/default/keyboard
    dpkg-reconfigure keyboard-configuration
    echo "Configured Capsloc"
  fi
}

function DotFiles() {
  stow --target=$HOME \
    bash \
    bash.ubuntu \
    bat \
    git \
    tmux \
    vim \
    nvim \
    toilet \
    visidata \
    lf \
    nb \
    vis \
    w3m \
    local-bin \
    snippets \
    ctags \
    zsh \
    subversion \
    readline \
    kak \
    helix \
    less \
    info \
    newsboat \
    nushell
}

Main "$@"
