#!/usr/bin/env bash

# To use this prompt, add the following to your bash config file.
#
#     source ~/.bash_prompt
#
# Your bash config file is ~/.bash_profile.

# Colour attribute codes

# See `man terminfo` for the codes to send
# NOTE: Surround non-printing characters like `\[...\]`
RESET="\[$(tput sgr0)\]"
RED="\[$(tput setaf 1)\]"
GREEN="\[$(tput setaf 2)\]"
BLUE="\[$(tput setaf 4)\]"
LOLIGHT="\[$(tput bold)\]\[$(tput setaf 0)\]"

# Functions

function PromptPS1() {
  local exit="$(PromptExitInfo)"
  PS1="${BLUE}»${RESET} $(PromptHistoryInfo)\W $(PromptGitInfo)${exit}\$ "
}

function PromptGitInfo() {
  local branch="$(GitCurrentBranch)"
  [[ -n "$branch" ]] && printf "${GREEN}(${branch})${RESET} "
}

function PromptExitInfo() {
  local exitCode="$?"
  [[ $SECONDS -le 1 ]] && exit # HACK: Exit code is 1 when shell starts
  [[ $exitCode != 0 ]] && printf "${RED}${exitCode}${RESET} "
}

function PromptHistoryInfo() {
  printf "${LOLIGHT}!\!${RESET} "
}

function GitCurrentBranch() {
  git branch 2>/dev/null | sed -e '/^[^*]/d; s/^* //'
}

# Prompt

export PROMPT_COMMAND="PromptPS1"
