#!/usr/bin/env bash

# To use this prompt, add the following to your bash config file.
#
#     source ~/.bash_prompt
#
# Your bash config file is ~/.bash_profile.

# Colour attribute codes

# See `man terminfo` for the codes to send
# NOTE: Surround non-printing characters like `\[...\]`
RESET="\[$(tput sgr0)\]"
RED="\[$(tput setaf 1)\]"
GREEN="\[$(tput setaf 2)\]"
BLUE="\[$(tput setaf 4)\]"
LOLIGHT="\[$(tput bold)\]\[$(tput setaf 0)\]"

# Functions

function PromptPS1() {
  local exit="$(PromptExitInfo)"
  PS1="${BLUE}»${RESET} $(PromptHistoryInfo)\W $(PromptGitInfo)$(PromptLfInfo)$(PromptNixInfo)$(PromptVenvInfo)${exit}\$ "
}


function PromptGitInfo() {
  local branch="$(GitCurrentBranch)"
  [[ -n "$branch" ]] && printf "${GREEN}(${branch})${RESET} "
}

function PromptExitInfo() {
  local exitCode="$?"
  [[ $SECONDS -le 1 ]] && exit # HACK: Exit code is 1 when shell starts
  [[ $exitCode != 0 ]] && printf "${RED}${exitCode}${RESET} "
}

function PromptHistoryInfo() {
  printf "${LOLIGHT}!\!${RESET} "
}

function PromptLfInfo() {
  [[ -n "$LF_LEVEL" ]] && printf "${LOLIGHT}(lf$LF_LEVEL)${RESET} "
}

function PromptNixInfo() {
  # Checking the PATH seems crude, but can't find any other indicators
  [[ $PATH =~ "/nix/store/" ]] && printf "${LOLIGHT}(nix)${RESET} "
}

function PromptVenvInfo() {
  [[ -n "$VIRTUAL_ENV_PROMPT" ]] && printf "${LOLIGHT}(venv)${RESET} "
}

function PromptShlvlInfo() {
  # tmux intial shell has $SHLVL == 3 (shell + tmux + tmux shell?)
  local baseShlvl=$([[ -n "$TMUX" ]] && echo 3 || echo 1)
  local extraShells=$(( $SHLVL - $baseShlvl ))
  [[ $extraShells -gt 0 ]] && printf "${LOLIGHT}(SHLVL+${extraShells})${RESET} "
}

function GitCurrentBranch() {
  # Once Git >= v2.2:
  # git branch --show-current 2>/dev/null
  git rev-parse --abbrev-ref HEAD 2>/dev/null
}

# Prompt

export PROMPT_COMMAND="PromptPS1"
