#!/usr/bin/env bash

# Handy command aliases to make terminal more pleasant

# some more ls aliases
alias  l='ls --color=auto -AFl --group-directories-first'
alias ll='ls --color=auto -AFl --group-directories-first'
alias la='ls --color=auto -AF  --group-directories-first'

# Simpler navigation up
alias   ..='cd ..'          # Go up one directory
alias  ...='cd ../..'       # Go up two directories
alias ....='cd ../../..'    # And for good measure

# Safer rm
alias rm='rm -I'

# Simple tree view
alias    t='tree -aFC -I .git --dirsfirst -L 1'
alias   tt='tree -aFC -I .git --dirsfirst -L 2'
alias  ttt='tree -aFC -I .git --dirsfirst -L 3'
alias tree='tree -aFC -I .git --dirsfirst'

# List shell completions
alias list_aliases='compgen -A alias | sort -u'
alias list_commands='compgen -A command | sort -u'
alias list_functions='compgen -A function | sort -u'
alias list_users='compgen -A user | sort -u'
alias list_variables='compgen -A variable | sort -u'

# Text format conversions
alias ascii2base64="convert-text --format base64"
alias base642ascii="convert-text --format base64 --decode"
alias ascii2hex="convert-text --format hex"
alias hex2ascii="convert-text --format hex --decode"
alias ascii2dec="convert-text --format dec"
alias dec2ascii="convert-text --format dec --decode"
alias ascii2bin="convert-text --format bin"
alias bin2ascii="convert-text --format bin --decode"

# Date
alias localdate='datetime localdate'
alias isodate='datetime isodate'
alias isostamp='datetime isostamp'

# Tmux
alias tm='tmux -CC new-session -As'  # iTerm2 (control mode and reuse session)
alias ta='tmux-attach'
alias tp='tmux-project --dir ~/projects'
alias ts='tmux-shared'
alias tsl='tmux-shared --local'

# Vim
alias v='vim'
alias vs='vim-session --dir ~/sessions'

# Interactive file system browsers
alias f="file-browser"
alias d="directory-browser"
alias s="text-browser"
alias p="paginate"
alias r="render"

# Clear script and start afresh
alias c="clear && motd"
alias cl="clear && ruler"

# Interactive timezone picker
alias tz="timezones --pretty --browse"

# Find current weather forecast
alias wttr="weather-forecast"

# Git (and some FZF)
alias g="git st"
alias ga="git patch"
alias gc="git browse-branches"
alias gco="git co"
alias gd="git browse-diff"
alias gl="git browse-log2"
alias glg="git browse-log"
alias gp="git push"
alias gtd="git browse-file-diffs"
alias gtt="git browse-file-versions"
alias gwt="source git-worktree-switch"

# nb shorcuts
alias nbj="nb-journal"

# FZF keyboard shortcuts
alias keys="source list-keys"

# Dockerised tools
# alias elm="docker-elm"
alias asciicast2gif="docker-asciicast2gif"

# Helper to join args by a separator
function join_by() {
  local IFS="$1"
  shift
  echo "$*"
}

# Watch in colour with configurable interval
function wtch {
  local -r interval="$1"
  shift

  \watch --interval "$interval" --color faketty "$@"
}
