#!/usr/bin/env bash

# Complete the word at current location in the readline.
# Usage: readline-complete <cmd>
# <cmd> is the name of command to use to pick a completion.
# <cmd> will be called with the current word prefix as the only parameter.
function readline-complete() {
  local cmd="$@"

  # Read the line
  local start="${READLINE_LINE:0:$READLINE_POINT}"
  local end="${READLINE_LINE:$READLINE_POINT}"

  # Find the completion
  local currentWord="${start##* }"
  local prefix="${start:0:$(( ${#start} - ${#currentWord} ))}"
  local result="$($cmd "$currentWord")"

  # Nothing to do if nothing selected
  if [[ -z "$result" ]]; then return; fi

  # Update line to complete/replace the current word
  READLINE_LINE="${prefix}${result}${end}"
  READLINE_POINT=$(( ${#prefix} + ${#result} ))
}

# Select a file using fzf (fzf-file-widget minus the READLINE handling)
function fzf-file() {
  __fzf_select__ --query "$@"
}

# CTRL-x CTRL-f - Complete/replace the current word with file paths
bind -m emacs-standard -x '"\C-x\C-f": readline-complete fzf-file'
bind -m vi-command -x     '"\C-x\C-f": readline-complete fzf-file'
bind -m vi-insert -x      '"\C-x\C-f": readline-complete fzf-file'

# CTRL-x CTRL-g - Complete/replace the current word with interesting git files
bind -m emacs-standard -x '"\C-x\C-g": readline-complete git-interesting-files'
bind -m vi-command -x     '"\C-x\C-g": readline-complete git-interesting-files'
bind -m vi-insert -x      '"\C-x\C-g": readline-complete git-interesting-files'

# CTRL-x CTRL-k - Complete/replace the current word with dictionary words
bind -m emacs-standard -x '"\C-x\C-k": readline-complete words'
bind -m vi-command -x     '"\C-x\C-k": readline-complete words'
bind -m vi-insert -x      '"\C-x\C-k": readline-complete words'

# CTRL-x CTRL-l - Complete/replace the current word with previous lines
bind -m emacs-standard -x '"\C-x\C-l": readline-complete tmux-line'
bind -m vi-command -x     '"\C-x\C-l": readline-complete tmux-line'
bind -m vi-insert -x      '"\C-x\C-l": readline-complete tmux-line'

# CTRL-x CTRL-p - Complete/replace the current word with previous words
bind -m emacs-standard -x '"\C-x\C-p": readline-complete tmux-word'
bind -m vi-command -x     '"\C-x\C-p": readline-complete tmux-word'
bind -m vi-insert -x      '"\C-x\C-p": readline-complete tmux-word'

# CTRL-j - List current directory
bind -m emacs-standard -x '"\C-j": clear && pwd && l'

# Space - History expansion
bind -m emacs-standard 'Space: magic-space'
bind -m vi-command     'Space: magic-space'
bind -m vi-insert      'Space: magic-space'

# CTRL-x Enter - Shell expand line
bind -m emacs-standard '"\C-x\C-m": shell-expand-line'
bind -m vi-command     '"\C-x\C-m": shell-expand-line'
bind -m vi-insert      '"\C-x\C-m": shell-expand-line'
